import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

import { Counter } from "../components/counter";
import { EventList } from "../components/eventList";
import { Button } from "@chakra-ui/react";

// export async function getStaticProps() {
//   const res = await fetch('https://ar-museum-test.azurewebsites.net/api/function_extract?code=QDUxNgsgxUSskI0OzfHK73J7TogrS8EiPSj-qjf08WNvAzFuI2PKFA==')
//   const events = await res.json()

//   return {
//     props: {
//       events,
//     },
//     revalidate: 1,
//   }
// }

export default function Home() {
  const [events, setEvents] = useState([]);

  useEffect(() => {
    (async function () {
      var new_events = [];
      const res = await fetch("/api/events");
      new_events = await res.json();

      setEvents(new_events["events"]);
    })();
  }, [events]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          AR Museums
        </h1> */}

        <Button
          onClick={() => {
            fetch("/api/update_session");
          }}
          size="lg"
          m={4}
        >
          Start new session
        </Button>

        <EventList events={events} />
      </main>
    </div>
  );
}
